<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Login:login' => function () {
    return ($this->privates['service_locator.8crJbMu'] ?? $this->load(__DIR__.'/getServiceLocator_8crJbMuService.php'));
}, 'App\\Controller\\Tienda:addCarrito' => function () {
    return ($this->privates['service_locator.RSh3j3S'] ?? $this->load(__DIR__.'/getServiceLocator_RSh3j3SService.php'));
}, 'App\\Controller\\Tienda:carrito' => function () {
    return ($this->privates['service_locator.RSh3j3S'] ?? $this->load(__DIR__.'/getServiceLocator_RSh3j3SService.php'));
}, 'App\\Controller\\Tienda:deleteCarrito' => function () {
    return ($this->privates['service_locator.s6JY3QR'] ?? $this->load(__DIR__.'/getServiceLocator_S6JY3QRService.php'));
}, 'App\\Controller\\Tienda:menuPrincipal' => function () {
    return ($this->privates['service_locator.s6JY3QR'] ?? $this->load(__DIR__.'/getServiceLocator_S6JY3QRService.php'));
}, 'App\\Controller\\Login::login' => function () {
    return ($this->privates['service_locator.8crJbMu'] ?? $this->load(__DIR__.'/getServiceLocator_8crJbMuService.php'));
}, 'App\\Controller\\Tienda::addCarrito' => function () {
    return ($this->privates['service_locator.RSh3j3S'] ?? $this->load(__DIR__.'/getServiceLocator_RSh3j3SService.php'));
}, 'App\\Controller\\Tienda::carrito' => function () {
    return ($this->privates['service_locator.RSh3j3S'] ?? $this->load(__DIR__.'/getServiceLocator_RSh3j3SService.php'));
}, 'App\\Controller\\Tienda::deleteCarrito' => function () {
    return ($this->privates['service_locator.s6JY3QR'] ?? $this->load(__DIR__.'/getServiceLocator_S6JY3QRService.php'));
}, 'App\\Controller\\Tienda::menuPrincipal' => function () {
    return ($this->privates['service_locator.s6JY3QR'] ?? $this->load(__DIR__.'/getServiceLocator_S6JY3QRService.php'));
})));
