easy_admin:
    design:
      menu:
        - {label: 'Productos',  entity: 'Producto'}
        - {label: 'Usuarios', icon: 'users', entity: 'Usuario'}
        - {label: 'Categorias', entity: 'Categoria'}
        - {label: 'Pedidos', entity: 'PedidoProducto'}
        - {label: 'Volver', icon: 'delete', route: 'principal' }
    site_name: Mis productos
    entities:
      Producto:
        class: App\Entity\Producto
        list:
          fields: ['cod_prod', 'nombre', 'stock', 'precio', { property: 'categoria.nombre', label: 'Categoria' }]
      Usuario:
        class: App\Entity\Usuario
        list:
          fields:
            ['cod_usu', {property: 'correo', type: 'email'}, 'direccion', {label: 'Codigo Postal' ,property: 'CP', type: 'raw'},{property: 'telefono', type: 'tel'}, 'admin']
      Categoria:
        class: App\Entity\Categoria
        list:
            fields: ['cod_cat', 'nombre', 'productos']
      PedidoProducto:
        class: App\Entity\PedidoProducto
        list:
            fields: ['cod_ped_prod', 'cod_ped', 'cod_prod', 'unidades']