security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        LoginUsuarios:
          entity:
            class: App\Entity\Usuarios
            property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             anonymous: true
             form_login:
                login_path: login
                check_path: login
                default_target_path: main
                always_use_default_target_path: true
             provider: LoginUsuarios
             logout:
                path:   /logout
                target: /login
    access_control:
        - { path: ^/main, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
