security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
       App\Entity\Usuario:
          algorithm: plaintext
    providers:
        LoginUsuarios:
          entity:
            class: App\Entity\Usuario
            property: correo

    firewalls:
        main:
             anonymous: true
             form_login:
                login_path: login
                check_path: login
                default_target_path: principal
                always_use_default_target_path: true
             provider: LoginUsuarios
             logout:
                path:   /logout
                target: /
    role_hierarchy:
            ROLE_ADMIN: ROLE_USER
    access_control:
        - { path: ^/principal, roles: ROLE_USER }
        - { path: ^/zonaAdmin, roles: ROLE_ADMIN }
