#index:
#    path: /
#    controller: App\Controller\Login::login
logout:
    path: /logout
easy_admin_bundle:
            resource: "@EasyAdminBundle/Controller/"
            type:     annotation
            prefix:   /zonaAdmin