<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\EditprofileType' shared autowired service.

return $this->privates['App\Form\EditprofileType'] = new \App\Form\EditprofileType();
