<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEKASFNI\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEKASFNI/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEKASFNI.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEKASFNI\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEKASFNI\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EKASFNI',
    'container.build_id' => '370b2d63',
    'container.build_time' => 1520015614,
));
