<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGtX76zx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGtX76zx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGtX76zx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGtX76zx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGtX76zx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GtX76zx',
    'container.build_id' => 'cd4724ca',
    'container.build_time' => 1520094840,
));
