<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFz7qvyV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFz7qvyV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFz7qvyV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFz7qvyV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFz7qvyV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fz7qvyV',
    'container.build_id' => '70262b2b',
    'container.build_time' => 1519927878,
));
